language: python
python:
  - "3.9.1"
install: 
  - "pip install coverage"
  - "pip install periodictable"
  - "pip install codecov"
  - "pip install scipy"
  - "python setup.py install"
script: 
  - "pytest"
