build: false

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
    - PYTHON: "C:\Python38-x64"
    - PYTHON: "C:\Python39-x64"
    - PYTHON: "C:\Python310-x64"
init:
  - "ECHO %PYTHON%

install:
  - "%PYTHON%/python.exe -m pip install --upgrade pip"
  - "%PYTHON%/python.exe -m pip install pytest"
  - "%PYTHON%/python.exe -m pip install numpy"
  - "%PYTHON%/python.exe -m pip install scipy"
  - "%PYTHON%/python.exe -m pip install periodictable"
  - "%PYTHON%/python.exe -m pip install nose"
  - "%PYTHON%/python.exe -m pip install coverage"
  - "%PYTHON%/python.exe setup.py install"

test_script:
  - "%PYTHON%/python.exe -m pytest -v"
